### ISSUE TITLE
ModuleNotFoundError: No module named 'raylibpy'

### ISSUE THREAD

**Issue by Kaftorone** [overdev/raylib-py#48]
```
ModuleNotFoundError: No module named 'raylibpy'
```
any help

**Comment by overdev** [comment]
Do you have more than one Python version installed? It seems you've installed for one version and tryed to run your script on another. If raylib-py is not found, probably the bug is not on raylib-py.

on your terminal/command prompt, do the following:
ˋˋˋ
pip list
ˋˋˋ
and check if raylib-py is the list. If positive, make sure the python interpreter running you script is the same. On windows, you can type
```
py --version
```
On mac or linux, it probably is
```
python3 --version
```

Then, in your script, one line above where you import raylib, add:
```
import sys
print(sys.version)
```
If the versions are the same, you must provide more context. Otherwise, you must run the script with the correct python version/interpreter where raylib-py is installed.

**Comment by overdev** [comment]
@Kaftorone are you still having this problem?
